---
title: "R Notebook"
output: html_notebook
---

```{r}
# Setup Dataset
movies <- read.table("~/dataScience/movieLens.txt", quote="\"", header = FALSE, sep = "|")
str(movies)
colnames(movies) = c("ID", "Title", "ReleaseDate", "VideoReleaseDate", "IMDB", "Unknown", "Action", "Adventure", "Animation", "Children", "Comedy", "Crime", "Documentory", "Drama", "Fantasy", "FilmNoir", "Horror", "Musical", "Mistery", "Romance", "SciFi", "Thriller", "War", "Western")
str(movies)
movies$ID = NULL
movies$ReleaseDate = NULL
movies$VideoReleaseDate = NULL
movies$IMDB = NULL
movies = unique(movies)
str(movies)
table(movies$Comedy)
table(movies$Western)
table(movies$Romance, movies$Drama)
```

```{r}
distances <- dist(movies[2:20], method = "euclidean")
clusterMovies = hclust(distances, method = "ward.D")
plot(clusterMovies)
plot(as.dendrogram(clusterMovies))
clusterGroups = cutree(clusterMovies, k = 2)
# Approach to finding cluster centroid
tapply(movies$Action, clusterGroups, mean)
tapply(movies$Romance, clusterGroups, mean)
# Approach 2 using colMeans (one command for each cluster)
colMeans(subset(movies[2:20], clusterGroups == 1))
# Approach 3 using split
spl <- split(movies[2:20], clusterGroups)
spl[[1]] # same as subset(movies[2:20], clusterGroups == 1)
colMeans(spl[[1]]) # same as colMeans(subset(movies[2:20], clusterGroups == 1))
# Approach 4 using lapply(runs the second arg on all the elements of the first arg)
lapply(spl, colMeans)
subset(movies, Title == "Men in Black (1997)")
clusterGroups[257]
cluster2 <- subset(movies, clusterGroups == 2)
cluster2$Title[1:10]
```

